---
# tasks file for secrets
- name: Create secrets
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/secrets.j2') }}"
  no_log: false
- name: Create certificates
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/certificates.j2') }}"
  no_log: false