---
workspace: "{{ workspace }}"
namespace: "{{ namespace }}"
output_path: /tmp/ansible_tasks
desired_deployment_name: jenkins
helmchart_path: tmp/deploy_helms/sunat-cuc-jenkins-helmchart/

jenkins_ingressroute_dns: '{{ "jenkins.devops-internal.pre.dc1.sunat-cuc.peru"  if workspace == "shared" else  "jenkins.devops-internal.pre.dc1.sunat-cuc.peru" }}'
ingress_certificate_secret:  '{{ "sunat-wildcard-secret"  if workspace == "shared" else  "wildcard-nuevo" }}'

admin_user_credentials_secret: jenkins-admin-credentials-secret
admin_user_credentials_secret_userKey: jenkins-admin-user
admin_user_credentials_secret_passwordKey: jenkins-admin-password


admin_user_user_value: admin
admin_user_password_value: bkpKn4F70V

jenkins_image: jenkins/jenkins
jenkins_imageTag: 2.280-jdk11
jenkins_imagePullPolicy: IfNotPresent

jenkins_agentsCap: 15
jenkins_persistence: |
  storageClass: local-path-tools
  accessMode: "ReadWriteOnce"
  size: "80Gi"


jenkins_serviceType: ClusterIP
###observacion ambiente cuc###
jenkins_affinity: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/node-tools
            operator: In
            values:
            - ""
#################################
###observacion ambiente cuc###
jenkins_nodeSelector: |
    node-role.kubernetes.io/node-tools: ""
#################################
jenkins_installPlugins: |
  - ace-editor:1.1
  - ant:1.11
  - antisamy-markup-formatter:2.1
  - apache-httpcomponents-client-4-api:4.5.13-1.0
  - artifactory:3.10.6
  - authentication-tokens:1.4
  - azure-commons:1.1.2
  - bootstrap4-api:4.6.0-3
  - bouncycastle-api:2.20
  - branch-api:2.6.3
  - checks-api:1.6.2
  - cloudbees-disk-usage-simple:0.10
  - cloudbees-folder:6.15
  - command-launcher:1.5
  - config-file-provider:3.7.0
  - configuration-as-code:1.47
  - credentials:2.3.15
  - credentials-binding:1.24
  - display-url-api:2.3.4
  - docker-commons:1.17
  - durable-task:1.35
  - echarts-api:5.0.1-1
  - extended-read-permission:3.2
  - external-monitor-job:1.7
  - font-awesome-api:5.15.2-2
  - git:4.7.1
  - git-client:3.7.1
  - git-server:1.9
  - github:1.33.1
  - github-api:1.123
  - gitlab-plugin:1.5.20
  - gradle:1.36
  - greenballs:1.15.1
  - handlebars:3.0.8
  - ivy:2.1
  - jackson2-api:2.12.1
  - javadoc:1.6
  - jaxb:2.3.0.1
  - jdk-tool:1.5
  - job-dsl:1.77
  - jquery-detached:1.2.1
  - jquery3-api:3.5.1-3
  - jsch:0.1.55.2
  - junit:1.49
  - kubernetes:1.29.2
  - kubernetes-cd:2.3.1
  - kubernetes-cli:1.10.0
  - kubernetes-client-api:4.13.2-1
  - kubernetes-credentials:0.8.0
  - ldap:2.4
  - lockable-resources:2.10
  - mailer:1.34
  - matrix-auth:2.6.6
  - matrix-project:1.18
  - maven-plugin:3.9
  - metrics:4.0.2.7
  - momentjs:1.1.1
  - okhttp-api:3.14.9
  - pam-auth:1.6
  - pipeline-build-step:2.13
  - pipeline-graph-analysis:1.10
  - pipeline-input-step:2.12
  - pipeline-milestone-step:1.3.2
  - pipeline-model-api:1.8.4
  - pipeline-model-definition:1.8.4
  - pipeline-model-extensions:1.8.4
  - pipeline-rest-api:2.19
  - pipeline-stage-step:2.5
  - pipeline-stage-tags-metadata:1.8.4
  - pipeline-stage-view:2.19
  - pipeline-utility-steps:2.7.1
  - plain-credentials:1.7
  - plugin-util-api:2.1.0
  - popper-api:1.16.1-2
  - prometheus:2.0.8
  - run-condition:1.5
  - scm-api:2.6.4
  - script-security:1.76
  - skip-certificate-check:1.0
  - snakeyaml-api:1.27.0
  - sonar:2.13
  - ssh-credentials:1.18.1
  - structs:1.22
  - token-macro:2.15
  - trilead-api:1.0.13
  - variant:1.4
  - windows-slaves:1.7
  - workflow-aggregator:2.6
  - workflow-api:2.42
  - workflow-basic-steps:2.23
  - workflow-cps:2.90
  - workflow-cps-global-lib:2.18
  - workflow-durable-task-step:2.38
  - workflow-job:2.40
  - workflow-multibranch:2.23
  - workflow-scm-step:2.12
  - workflow-step-api:2.23
  - workflow-support:3.8
  - xml-job-to-job-dsl:0.1.13


jenkins_ingressroute: |
  redirect_http_to_https: true
  match: "Host(`{{ jenkins_ingressroute_dns }}`)"
  tls:
    domains:
    - main: {{ jenkins_ingressroute_dns }}
    secretName: {{ ingress_certificate_secret }}

jenkins_serviceAnnotations: |
  prometheus.io/path: /prometheus
  prometheus.io/port: "8080"
  prometheus.io/scheme: http
  prometheus.io/scrape: "true"

jenkins_resources: |
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "2000m"
    memory: "4096Mi"

jenkins_enableXmlConfig: true
jenkins_overwriteConfig: false
jenkins_overwriteJobs: false
jenkins_healthProbeLivenessInitialDelay: "300"
jenkins_healthProbeReadinessInitialDelay: "120"

jenkins_jobsasxml: |
  testJenkinsJob: |-
    <?xml version='1.1' encoding='UTF-8'?>
    <flow-definition plugin="workflow-job@2.39">
      <description></description>
      <keepDependencies>false</keepDependencies>
      <properties/>
      <definition class="org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition" plugin="workflow-cps@2.82">
        <script>podTemplate(label: &apos;jnlp-petclinic&apos;, slaveConnectTimeout: &apos;600&apos;, readOnlyRootFilesystem: true, runAsNonRoot: true, runAsUser: &apos;1000&apos;, envVars: [envVar(key: &apos;GIT_BRANCH&apos;, value: &apos;master&apos;)], containers: [
        containerTemplate(
                name: &apos;maven&apos;,
                image: &apos;maven:3.6.3-jdk-11&apos;,
                ttyEnabled: true,
                resourceLimitCpu: &apos;1000m&apos;,
                resourceLimitMemory: &apos;768Mi&apos;,
                resourceRequestCpu: &apos;250m&apos;,
                resourceRequestMemory: &apos;256Mi&apos;,
                command: &apos;cat&apos;,
                envVars: [
                ]
        )
    ]
    ) {
        node(&apos;jnlp-petclinic&apos;) {
            stage(&apos;Hello World&apos;) {
                container(&apos;maven&apos;) {
                  stage(&apos;Hello from Jenkins&apos;) {
                      sh &apos;&apos;&apos;#!/bin/bash
                      echo Hello From Ephemeral Agent
                      &apos;&apos;&apos;
                  }
                }
            }
          }
      }
    </script>
        <sandbox>true</sandbox>
      </definition>
      <triggers/>
      <disabled>false</disabled>
    </flow-definition>